// <auto-generated />
using System;
using L07_Api_Car.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L07ApiCar.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L07_Api_Car.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("GearBox")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fuel = "Pertol",
                            GearBox = "Manual",
                            Make = "Make1",
                            Model = "Model1",
                            PlateNumber = "ABC001",
                            Year = new DateTime(2022, 12, 5, 20, 24, 24, 955, DateTimeKind.Local).AddTicks(6168)
                        },
                        new
                        {
                            Id = 2,
                            Fuel = "Diesel",
                            GearBox = "Automatic",
                            Make = "Make2",
                            Model = "Model2",
                            PlateNumber = "ABC002",
                            Year = new DateTime(2022, 12, 5, 20, 24, 24, 958, DateTimeKind.Local).AddTicks(2154)
                        },
                        new
                        {
                            Id = 3,
                            Fuel = "Electric",
                            GearBox = "Manual",
                            Make = "Make3",
                            Model = "Model3",
                            PlateNumber = "ABC003",
                            Year = new DateTime(2022, 12, 5, 20, 24, 24, 958, DateTimeKind.Local).AddTicks(2179)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
