// <auto-generated />
using System;
using L05_Tasks_MSSQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L05TasksMSSQL.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20221130200700_addedCreatedAndUpdatedToBook")]
    partial class addedCreatedAndUpdatedToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ECoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Marcel Proust",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(991),
                            ECoverType = "Paperback",
                            PublishYear = 2001,
                            Title = "In Search of Lost Time",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1055)
                        },
                        new
                        {
                            Id = 2,
                            Author = "James Joyce",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1060),
                            ECoverType = "Hardcover",
                            PublishYear = 2002,
                            Title = "Ulysses",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1062)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Miguel de Cervantes",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1064),
                            ECoverType = "Electronic",
                            PublishYear = 2003,
                            Title = "Don Quixote",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1066)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Gabriel Garcia Marquez",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1068),
                            ECoverType = "Hardcover",
                            PublishYear = 2004,
                            Title = "One Hundred Years of Solitude",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1070)
                        },
                        new
                        {
                            Id = 5,
                            Author = "F. Scott Fitzgerald",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1071),
                            ECoverType = "Hardcover",
                            PublishYear = 2005,
                            Title = "The Great Gatsby",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1073)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1075),
                            ECoverType = "Paperback",
                            PublishYear = 2006,
                            Title = "Moby Dick",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1077)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Leo Tolstoy",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1078),
                            ECoverType = "Paperback",
                            PublishYear = 2007,
                            Title = "War and Peace",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1080)
                        },
                        new
                        {
                            Id = 8,
                            Author = "William Shakespeare",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1082),
                            ECoverType = "Hardcover",
                            PublishYear = 2008,
                            Title = "Hamlet",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1084)
                        },
                        new
                        {
                            Id = 9,
                            Author = "William Shakespeare",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1085),
                            ECoverType = "Hardcover",
                            PublishYear = 2009,
                            Title = "King Lear",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1087)
                        },
                        new
                        {
                            Id = 10,
                            Author = "William Shakespeare",
                            Created = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1089),
                            ECoverType = "Paperback",
                            PublishYear = 2010,
                            Title = "The Tempest",
                            Updated = new DateTime(2022, 11, 30, 22, 7, 0, 447, DateTimeKind.Local).AddTicks(1090)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
