// <auto-generated />
using System;
using L05_Tasks_MSSQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L05TasksMSSQL.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20221210133019_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableBooksInLibrary")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ECoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Marcel Proust",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2803),
                            ECoverType = "Paperback",
                            PublishYear = 2001,
                            Title = "In Search of Lost Time",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2837)
                        },
                        new
                        {
                            Id = 2,
                            Author = "James Joyce",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2842),
                            ECoverType = "Hardcover",
                            PublishYear = 2002,
                            Title = "Ulysses",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2843)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Miguel de Cervantes",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2845),
                            ECoverType = "Electronic",
                            PublishYear = 2003,
                            Title = "Don Quixote",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2847)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Gabriel Garcia Marquez",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2849),
                            ECoverType = "Hardcover",
                            PublishYear = 2004,
                            Title = "One Hundred Years of Solitude",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2850)
                        },
                        new
                        {
                            Id = 5,
                            Author = "F. Scott Fitzgerald",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2852),
                            ECoverType = "Hardcover",
                            PublishYear = 2005,
                            Title = "The Great Gatsby",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2854)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2856),
                            ECoverType = "Paperback",
                            PublishYear = 2006,
                            Title = "Moby Dick",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2857)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Leo Tolstoy",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2859),
                            ECoverType = "Paperback",
                            PublishYear = 2007,
                            Title = "War and Peace",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2860)
                        },
                        new
                        {
                            Id = 8,
                            Author = "William Shakespeare",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2862),
                            ECoverType = "Hardcover",
                            PublishYear = 2008,
                            Title = "Hamlet",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2864)
                        },
                        new
                        {
                            Id = 9,
                            Author = "William Shakespeare",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2865),
                            ECoverType = "Hardcover",
                            PublishYear = 2009,
                            Title = "King Lear",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2867)
                        },
                        new
                        {
                            Id = 10,
                            Author = "William Shakespeare",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2869),
                            ECoverType = "Paperback",
                            PublishYear = 2010,
                            Title = "The Tempest",
                            Updated = new DateTime(2022, 12, 10, 15, 30, 19, 237, DateTimeKind.Local).AddTicks(2870)
                        });
                });

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.LibraryBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("LibraryBook");
                });

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.LibraryBook", b =>
                {
                    b.HasOne("L05_Tasks_MSSQL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
