// <auto-generated />
using System;
using L05_Tasks_MSSQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L05TasksMSSQL.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20221208180331_addedUser")]
    partial class addedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ECoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Marcel Proust",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9933),
                            ECoverType = "Paperback",
                            PublishYear = 2001,
                            Title = "In Search of Lost Time",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9973)
                        },
                        new
                        {
                            Id = 2,
                            Author = "James Joyce",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9981),
                            ECoverType = "Hardcover",
                            PublishYear = 2002,
                            Title = "Ulysses",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9982)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Miguel de Cervantes",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9984),
                            ECoverType = "Electronic",
                            PublishYear = 2003,
                            Title = "Don Quixote",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9986)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Gabriel Garcia Marquez",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9988),
                            ECoverType = "Hardcover",
                            PublishYear = 2004,
                            Title = "One Hundred Years of Solitude",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9990)
                        },
                        new
                        {
                            Id = 5,
                            Author = "F. Scott Fitzgerald",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9992),
                            ECoverType = "Hardcover",
                            PublishYear = 2005,
                            Title = "The Great Gatsby",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9993)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9995),
                            ECoverType = "Paperback",
                            PublishYear = 2006,
                            Title = "Moby Dick",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9997)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Leo Tolstoy",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 477, DateTimeKind.Local).AddTicks(9999),
                            ECoverType = "Paperback",
                            PublishYear = 2007,
                            Title = "War and Peace",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 478, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Author = "William Shakespeare",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 478, DateTimeKind.Local).AddTicks(2),
                            ECoverType = "Hardcover",
                            PublishYear = 2008,
                            Title = "Hamlet",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 478, DateTimeKind.Local).AddTicks(4)
                        },
                        new
                        {
                            Id = 9,
                            Author = "William Shakespeare",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 478, DateTimeKind.Local).AddTicks(6),
                            ECoverType = "Hardcover",
                            PublishYear = 2009,
                            Title = "King Lear",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 478, DateTimeKind.Local).AddTicks(7)
                        },
                        new
                        {
                            Id = 10,
                            Author = "William Shakespeare",
                            Created = new DateTime(2022, 12, 8, 20, 3, 31, 478, DateTimeKind.Local).AddTicks(9),
                            ECoverType = "Paperback",
                            PublishYear = 2010,
                            Title = "The Tempest",
                            Updated = new DateTime(2022, 12, 8, 20, 3, 31, 478, DateTimeKind.Local).AddTicks(11)
                        });
                });

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
