// <auto-generated />
using L05_Tasks_MSSQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L05TasksMSSQL.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20221129185104_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Marcel Proust",
                            ECoverType = "Paperback",
                            PublishYear = 2001,
                            Title = "In Search of Lost Time"
                        },
                        new
                        {
                            Id = 2,
                            Author = "James Joyce",
                            ECoverType = "Hardcover",
                            PublishYear = 2002,
                            Title = "Ulysses"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Miguel de Cervantes",
                            ECoverType = "Electronic",
                            PublishYear = 2003,
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Gabriel Garcia Marquez",
                            ECoverType = "Hardcover",
                            PublishYear = 2004,
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Id = 5,
                            Author = "F. Scott Fitzgerald",
                            ECoverType = "Hardcover",
                            PublishYear = 2005,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            ECoverType = "Paperback",
                            PublishYear = 2006,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Leo Tolstoy",
                            ECoverType = "Paperback",
                            PublishYear = 2007,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 8,
                            Author = "William Shakespeare",
                            ECoverType = "Hardcover",
                            PublishYear = 2008,
                            Title = "Hamlet"
                        },
                        new
                        {
                            Id = 9,
                            Author = "William Shakespeare",
                            ECoverType = "Hardcover",
                            PublishYear = 2009,
                            Title = "King Lear"
                        },
                        new
                        {
                            Id = 10,
                            Author = "William Shakespeare",
                            ECoverType = "Paperback",
                            PublishYear = 2010,
                            Title = "The Tempest"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
