// <auto-generated />
using System;
using L04_EF_Applying_To_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L04EFApplyingToAPI.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20221208173710_UpdatedPasswordsAndAddedRole")]
    partial class UpdatedPasswordsAndAddedRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("L04_EF_Applying_To_API.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpiceLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Country = "Lithuania",
                            CreatedDateTime = new DateTime(2022, 12, 8, 19, 37, 10, 319, DateTimeKind.Local).AddTicks(312),
                            ImagePath = "",
                            Name = "Fried bread sticks",
                            SpiceLevel = "Low",
                            Type = "Snacks",
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = 2,
                            Country = "Lithuania",
                            CreatedDateTime = new DateTime(2022, 12, 8, 19, 37, 10, 319, DateTimeKind.Local).AddTicks(358),
                            ImagePath = "",
                            Name = "Potatoe dumplings",
                            SpiceLevel = "Low",
                            Type = "Main dish",
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = 3,
                            Country = "Lithuania",
                            CreatedDateTime = new DateTime(2022, 12, 8, 19, 37, 10, 319, DateTimeKind.Local).AddTicks(361),
                            ImagePath = "",
                            Name = "Kibinai",
                            SpiceLevel = "Low",
                            Type = "Street food",
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("L04_EF_Applying_To_API.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("L04_EF_Applying_To_API.Models.RecipeItem", b =>
                {
                    b.Property<int>("RecipeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Calories")
                        .HasColumnType("REAL");

                    b.Property<int>("DishId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeItemId");

                    b.HasIndex("DishId");

                    b.ToTable("RecipeItems");

                    b.HasData(
                        new
                        {
                            RecipeItemId = 1,
                            Calories = 120.0,
                            DishId = 1,
                            Name = "Bread"
                        },
                        new
                        {
                            RecipeItemId = 2,
                            Calories = 50.0,
                            DishId = 1,
                            Name = "Cheese"
                        },
                        new
                        {
                            RecipeItemId = 3,
                            Calories = 200.0,
                            DishId = 1,
                            Name = "Mayo"
                        },
                        new
                        {
                            RecipeItemId = 4,
                            Calories = 14.0,
                            DishId = 1,
                            Name = "Garlic"
                        },
                        new
                        {
                            RecipeItemId = 5,
                            Calories = 600.0,
                            DishId = 2,
                            Name = "Potatoes"
                        },
                        new
                        {
                            RecipeItemId = 6,
                            Calories = 420.0,
                            DishId = 2,
                            Name = "Meat"
                        },
                        new
                        {
                            RecipeItemId = 7,
                            Calories = 180.0,
                            DishId = 2,
                            Name = "Sour cream"
                        },
                        new
                        {
                            RecipeItemId = 8,
                            Calories = 120.0,
                            DishId = 3,
                            Name = "Dough"
                        },
                        new
                        {
                            RecipeItemId = 9,
                            Calories = 120.0,
                            DishId = 3,
                            Name = "Meat"
                        },
                        new
                        {
                            RecipeItemId = 10,
                            Calories = 120.0,
                            DishId = 3,
                            Name = "Salt"
                        });
                });

            modelBuilder.Entity("L04_EF_Applying_To_API.Models.RecipeItem", b =>
                {
                    b.HasOne("L04_EF_Applying_To_API.Models.Dish", "Dish")
                        .WithMany("RecipeItems")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("L04_EF_Applying_To_API.Models.Dish", b =>
                {
                    b.Navigation("RecipeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
